language: perl
sudo: false

addons:
  apt:
    packages:
      - nettle-dev

install:
  - perlbrew list
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps   --missing | cpanm -n
  - cpanm -n App::af
  - af missing | cpanm -n

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"

script:
  - dzil test -v

env:
  - ALIEN_INSTALL_TYPE=share
  - ALIEN_INSTALL_TYPE=system
